apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdu-evac-backend
  template:
    metadata:
      labels:
        app: sdu-evac-backend
    spec:
      containers:
      - image: sdu-evac-backend
        name: sdu-evac-backend
        imagePullPolicy: IfNotPresent
        resources:
          requests:
           memory: "150Mi"
           cpu: "100m"
          limits:
            memory: "285Mi"
            cpu: "285m"
        livenessProbe:
            httpGet:
              path: /health
              port: 80
            timeoutSeconds: 18
            periodSeconds: 10
            initialDelaySeconds: 120
        readinessProbe:
            httpGet:
              path: /health
              port: 80
            timeoutSeconds: 18
            periodSeconds: 10
            initialDelaySeconds: 50
        env:
        - name: PORT
          value: "80"
        - name: MONGO_DB_CONNECTION_STRING
          value: mongodb://mongodb:27017
        - name: MONGO_DB_NAME
          value: sdu-evac
        - name: REDIS_URI
          value: redis://redis-master


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdu-evac-backend
  name: sdu-evac-backend
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sdu-evac-backend
  type: NodePort

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sdu-evac-backend
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60